### ISSUE TITLE
Cert chains (e.g. with client/server cert + intermediate CA certs) do not seem to be supported

### ISSUE THREAD

**Issue by Alphix** [oracle/ktls-utils#44]
In a test environment, I have a root CA, intermediate CA and the certs for the server/client (signed by the intermediate CA).

The root CA is in the system-wide trust store (`/etc/ssl/certs`), but the intermediate CA is not.

If I configure `/etc/tlshd.conf` on the server/client with `x509.certificate=` pointing to a bundle with the intermediate and server/client cert, things don't work (the log says the cert isn't trusted).

If I manually add the intermediate CA to `/etc/ssl/certs`, everything works as expected.

**Comment by chucklever** [comment]
Our bake-a-thon test CA has a root and intermediate, so IIUC I test this scenario all the time. I think you might need to separate the certificate and the CA bundle. This is the server clause in my /etc/tlshd.conf:

```
[authenticate.server]
x509.truststore=/etc/pki/tls/certs/bakeathon-ca.pem
x509.certificate=/etc/pki/tls/certs/manet.server.cert.pem
x509.private_key=/etc/pki/tls/private/tlshd.key
```

**Comment by Alphix** [comment]
> Our bake-a-thon test CA has a root and intermediate, so IIUC I test this scenario all the time. I think you might need to separate the certificate and the CA bundle. This is the server clause in my /etc/tlshd.conf:
> 
> ```
> [authenticate.server]
> x509.truststore=/etc/pki/tls/certs/bakeathon-ca.pem
> x509.certificate=/etc/pki/tls/certs/manet.server.cert.pem
> x509.private_key=/etc/pki/tls/private/tlshd.key
> ```

Yes, I just built a version of `ktls-utils` from git sources, and setting `x509.truststore=` to point at the intermediate CA *does* work. But shouldn't it be possible for the client/server to serve up a bundle cert including both the intermediate CA cert and the client/server cert and just have the root CA in the system-wide trust? Or am I misunderstanding something....?

**Comment by chucklever** [comment]
> But shouldn't it be possible for the client/server
> to serve up a bundle cert including both the
> intermediate CA cert and the client/server cert
> and just have the root CA in the system-wide
> trust? Or am I misunderstanding something....?

Wouldn't you just point the trust= and certificate= pathnames to the same file?

Anyway, my understanding is that the GnuTLS library would need to handle the details of this. Do you know if it does?

**Comment by Alphix** [comment]
> Wouldn't you just point the trust= and certificate= pathnames to the same file?

No, I'm not a x509/GnuTLS expert, but that wouldn't really be correct (since the `certificate=` is about what the client presents to the server and vice versa)

> Anyway, my understanding is that the GnuTLS library would need to handle the details of this. Do you know if it does?

It does. And I've been digging into this a bit. The client doesn't send the whole cert chain to the server and vice versa. Only one cert from the file gets transmitted.

The reason seems to be the use of `gnutls_pcert_import_x509_raw` in `tlshd_config_get_client_cert()` and `tlshd_config_get_server_cert()` in `config.c`, which will only fetch one cert from the `.pem` file (which may contain more than one cert, in case of chained certs).

That can probably be addressed by using `gnutls_pcert_list_import_x509_raw` instead. I'll work on a patch and see if my hunch is correct.

**Comment by chucklever** [comment]
> > Wouldn't you just point the trust= and certificate= pathnames to the same file?
> 
> No, I'm not a x509/GnuTLS expert, but that wouldn't really be correct (since the `certificate=` is about what the client presents to the server and vice versa)

If you put it that way: you are telling GnuTLS to present a bundle, rather than a single cert, to the remote peer. I still don't see how it would make much difference.

Probably a better argument would be: certificate= contains the identity of the peer (and thus is expected to contain a single cert) and bundle= is the trust chain.

> > Anyway, my understanding is that the GnuTLS library would need to handle the details of this. Do you know if it does?
> 
> It does. And I've been digging into this a bit. The client doesn't send the whole cert chain to the server and vice versa. Only one cert from the file gets transmitted.
> 
> The reason seems to be the use of `gnutls_pcert_import_x509_raw` in `tlshd_config_get_client_cert()` and `tlshd_config_get_server_cert()` in `config.c`, which will only fetch one cert from the `.pem` file (which may contain more than one cert, in case of chained certs).
> 
> That can probably be addressed by using `gnutls_pcert_list_import_x509_raw` instead. I'll work on a patch and see if my hunch is correct.

I'll have a look at your PR. If that change doesn't result in a regression, I don't have an objection to merging it.

**Comment by Alphix** [comment]
> > > Wouldn't you just point the trust= and certificate= pathnames to the same file?
> > 
> > 
> > No, I'm not a x509/GnuTLS expert, but that wouldn't really be correct (since the `certificate=` is about what the client presents to the server and vice versa)
> 
> If you put it that way: you are telling GnuTLS to present a bundle, rather than a single cert, to the remote peer. I still don't see how it would make much difference.
> 
> Probably a better argument would be: certificate= contains the identity of the peer (and thus is expected to contain a single cert) and bundle= is the trust chain.

I'd put it as `certificate=` contains everything the client needs to present to the server (or vice versa) to prove that it's trusted (i.e. a certificate *or* a certificate chain). `trust=` is for the other side of the connection and sets up the trust anchor (which might lead to a validated cert by starting at the trust roots and possibly walking a cert chain). So `trust=` and `certificate=` wouldn't normally point to the same file. Anyway, I think we're on the same page and it should be clearer when you look at the PR.

> > It does. And I've been digging into this a bit. The client doesn't send the whole cert chain to the server and vice versa.
...
> > That can probably be addressed by using `gnutls_pcert_list_import_x509_raw` instead. I'll work on a patch and see if my hunch is correct.
> 
> I'll have a look at your PR. If that change doesn't result in a regression, I don't have an objection to merging it.

Good 😄
